// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/paper-plane-hero/CornerStatic.tsx": () => import("../components/mockups/paper-plane-hero/CornerStatic.tsx"),
  "./components/mockups/paper-plane-hero/DiagonalTrail.tsx": () => import("../components/mockups/paper-plane-hero/DiagonalTrail.tsx"),
  "./components/mockups/paper-plane-hero/FloatingAnimated.tsx": () => import("../components/mockups/paper-plane-hero/FloatingAnimated.tsx")
};
