export const PHASES = [
  {
    number: 1,
    name: "IDEIA",
    motivation: "Defina para quem você está construindo e prove que existe mercado real antes de escrever a primeira linha de código",
    tagline: "9 entregáveis estratégicos",
    artifacts: [
      { key: "SELETOR_NICHO_INICIAL", label: "Seletor de Nicho Inicial", icon: "crosshair", description: "Ranqueamento dos 5-8 segmentos candidatos por critérios objetivos" },
      { key: "LEAN_CANVAS", label: "Lean Canvas", icon: "grid", description: "9 blocos do modelo de negócio" },
      { key: "JTBD", label: "Tarefa do Cliente (JTBD)", icon: "target", description: "O que o cliente realmente quer realizar" },
      { key: "ANALISE_COMPETITIVA", label: "Análise Competitiva", icon: "bar-chart", description: "5 concorrentes mapeados com tabela comparativa" },
      { key: "MATRIZ_COMPETITIVA", label: "Matriz Competitiva 2×2", icon: "layout-grid", description: "Posicionamento visual em 2 eixos das prioridades do cliente" },
      { key: "DIMENSIONAMENTO_MERCADO", label: "TAM / SAM / SOM", icon: "pie-chart", description: "Tamanho real do mercado bottom-up" },
      { key: "HIPOTESE_CENTRAL", label: "Hipótese Central", icon: "zap", description: "Aposta principal em 1 frase testável" },
      { key: "VALIDACAO_RAPIDA", label: "Script de Validação", icon: "message-square", description: "10 perguntas de entrevista para validar a hipótese" },
      { key: "SCORE_POTENCIAL", label: "Score de Potencial", icon: "star", description: "Avaliação 1-5 em 5 dimensões com recomendação" },
    ],
    gates: [
      "Nicho inicial selecionado com TAM bottom-up calculado",
      "Hipótese central escrita em 1 frase testável",
      "Score de potencial médio ≥ 3.5",
    ],
  },
  {
    number: 2,
    name: "PRD",
    motivation: "Defina exatamente o que será construído, por que o cliente vai pagar e se a economia fecha",
    tagline: "10 entregáveis de produto, valor e economia",
    sections: [
      { id: "cliente-valor", label: "2A · Cliente & Valor", keys: ["PRD", "CARTAO_PERSONA", "MAPA_DECISAO_COMPRA", "VALOR_QUANTIFICADO", "USER_STORIES", "BENCHMARKING"] },
      { id: "modelo-economia", label: "2B · Modelo & Economia", keys: ["METRICAS_SUCESSO", "HIPOTESE_PRICING", "LTV_CAC", "ROADMAP_3_MESES"] },
    ],
    artifacts: [
      { key: "PRD", label: "Product Requirements Document", icon: "file-text", description: "Escopo, núcleo do produto e critérios de sucesso" },
      { key: "CARTAO_PERSONA", label: "Cartão de Persona", icon: "users", description: "Persona estruturada: bio, dia típico, gatilhos, watering holes" },
      { key: "MAPA_DECISAO_COMPRA", label: "Mapa de Decisão de Compra", icon: "git-branch", description: "Quem usa, quem aprova, quem paga, quem veta" },
      { key: "VALOR_QUANTIFICADO", label: "Valor Quantificado", icon: "calculator", description: "Situação atual → situação possível → ganho em $ ou horas" },
      { key: "USER_STORIES", label: "User Stories", icon: "list", description: "15 user stories com critérios de aceitação" },
      { key: "BENCHMARKING", label: "Benchmarking", icon: "globe", description: "3 referências globais com o que copiar e evitar" },
      { key: "METRICAS_SUCESSO", label: "Framework de Métricas", icon: "trending-up", description: "North Star, inputs, guardrails e AARRR" },
      { key: "HIPOTESE_PRICING", label: "Modelo de Precificação", icon: "dollar-sign", description: "3 tiers com 3 perguntas-chave de pricing" },
      { key: "LTV_CAC", label: "Calculadora LTV ÷ CAC", icon: "percent", description: "Unit economics com veredito de viabilidade" },
      { key: "ROADMAP_3_MESES", label: "Roadmap 3 Meses", icon: "map", description: "Plano trimestral com objetivos e entregas-chave" },
    ],
    gates: [
      "Persona, cliente-alvo e decisão de compra mapeados",
      "Valor quantificado em $ ou horas economizadas para o cliente",
      "LTV ÷ CAC projetado ≥ 3 (ou plano explícito para chegar lá)",
    ],
  },
  {
    number: 3,
    name: "SEGURANÇA & LGPD",
    motivation: "Mapeie riscos de segurança e requisitos legais antes de definir a arquitetura — decisões aqui condicionam o modelo de dados, APIs e infraestrutura",
    tagline: "8 entregáveis de segurança e privacidade",
    artifacts: [
      { key: "DATA_MAP", label: "Data Map + RAT", icon: "database", description: "Inventário de dados pessoais e Registro de Atividades de Tratamento (LGPD Art. 37)" },
      { key: "CLASSIFICACAO_DADOS", label: "Classificação de Dados", icon: "layers", description: "Públicos / internos / confidenciais / sensíveis (LGPD Art. 11)" },
      { key: "PRIVACY_BY_DESIGN", label: "Privacy by Design", icon: "shield", description: "Checklist dos 7 princípios aplicado a cada feature do PRD" },
      { key: "POLITICA_PRIVACIDADE", label: "Política de Privacidade + Consentimento", icon: "file-text", description: "Rascunho da política e fluxo de consentimento granular (LGPD Art. 8)" },
      { key: "THREAT_MODEL", label: "Threat Model (STRIDE)", icon: "alert-triangle", description: "Ameaças mapeadas por feature crítica com matriz de risco" },
      { key: "MATRIZ_RBAC", label: "Matriz RBAC", icon: "users", description: "Papéis × recursos × operações + fluxo de autenticação" },
      { key: "OWASP_CHECKLIST", label: "Checklist OWASP Top 10", icon: "check-square", description: "Top 10 adaptado à stack com controles de mitigação" },
      { key: "PLANO_INCIDENTES", label: "Plano de Resposta a Incidentes", icon: "bell", description: "Responsáveis, SLA ANPD 72h, política de logs e backup" },
    ],
    gates: [
      "Todos os dados pessoais mapeados com base legal LGPD definida para cada um",
      "Threat Model STRIDE documentado para as 3 features mais críticas do PRD",
      "Matriz RBAC e modelo de autenticação definidos e aprovados",
    ],
  },
  {
    number: 4,
    name: "SPEC",
    motivation: "Projete a arquitetura técnica antes de escrever a primeira linha de código",
    tagline: "8 entregáveis técnicos",
    artifacts: [
      { key: "ARQUITETURA", label: "Arquitetura do Sistema", icon: "cpu", description: "Stack, componentes, diagramas e trade-offs" },
      { key: "MODELO_DADOS", label: "Modelo de Dados", icon: "database", description: "Entidades, campos, índices e relacionamentos" },
      { key: "CONTRATOS_API", label: "Contratos de API", icon: "code", description: "8+ endpoints críticos documentados" },
      { key: "SEGURANCA", label: "Plano de Segurança", icon: "shield", description: "OWASP Top 10, LGPD, autenticação e auditoria" },
      { key: "FLUXOS_UI", label: "Fluxos de UX", icon: "layout", description: "5 fluxos críticos tela por tela com edge cases" },
      { key: "ESCALABILIDADE", label: "Plano de Escalabilidade", icon: "server", description: "Estratégia para 1K, 10K e 100K usuários" },
      { key: "ADR", label: "Architecture Decision Records", icon: "bookmark", description: "5 ADRs com contexto, decisão e consequências" },
      { key: "SETUP_DEVOPS", label: "DevOps & Infra", icon: "git-branch", description: "CI/CD, ambientes, observabilidade e custo estimado" },
    ],
    gates: [
      "Schema de dados completo e revisado",
      "Contratos de API definidos para todos os endpoints críticos",
      "Plano de segurança aprovado com LGPD endereçada",
    ],
  },
  {
    number: 5,
    name: "IMPLEMENTAÇÃO",
    motivation: "Quebre o produto em milestones navegáveis e construa com disciplina de engenharia",
    tagline: "7 entregáveis de engenharia",
    artifacts: [
      { key: "MILESTONES", label: "Plano de Milestones", icon: "flag", description: "5+ milestones com features, critérios e demos" },
      { key: "SPRINT_1", label: "Sprint 1 Detalhado", icon: "play", description: "Primeira semana hora a hora com bloqueadores mapeados" },
      { key: "ESTRUTURA_PASTAS", label: "Estrutura do Projeto", icon: "folder", description: "Árvore de arquivos comentada" },
      { key: "README", label: "README Completo", icon: "file", description: "Setup em 5 comandos, .env.example e contribuição" },
      { key: "GUIA_CONTRIBUICAO", label: "CONTRIBUTING.md", icon: "git-merge", description: "Padrões de código, PR checklist e convenção de commits" },
      { key: "TECH_DEBT_LOG", label: "Log de Débito Técnico", icon: "alert-triangle", description: "8+ atalhos documentados com plano de resolução" },
      { key: "DEFINITION_OF_DONE", label: "Definition of Done", icon: "check-square", description: "Critérios de conclusão para código, testes e deploy" },
    ],
    gates: [
      "Milestones quebrados em features entregáveis e testáveis",
      "README com setup funcionando em ≤ 15 minutos",
      "Zero mocks em features do caminho crítico",
    ],
  },
  {
    number: 6,
    name: "TESTE",
    motivation: "Valide que o produto funciona e que usuários reais conseguem usá-lo sem ajuda",
    tagline: "7 entregáveis de qualidade",
    artifacts: [
      { key: "PLANO_TESTES", label: "Plano de Testes", icon: "clipboard", description: "Estratégia, pirâmide, ferramentas e cobertura mínima" },
      { key: "CASOS_TESTE_CRITICOS", label: "20 Casos de Teste Críticos", icon: "check", description: "P0/P1/P2 priorizados com steps e resultados esperados" },
      { key: "CHECKLIST_QA", label: "Checklist de QA", icon: "list-checks", description: "Funcionalidade, performance, segurança, acessibilidade" },
      { key: "SCRIPT_USER_TEST", label: "Script de Teste com Usuários", icon: "user-check", description: "Roteiro para 5 testes reais com métricas de usabilidade" },
      { key: "RELATORIO_PERFORMANCE", label: "Benchmarks de Performance", icon: "activity", description: "Core Web Vitals, latência de API e carga suportada" },
      { key: "BUGS_PREVENCAO", label: "Top 10 Bugs a Prevenir", icon: "bug", description: "Causa raiz, impacto, prevenção e detecção" },
      { key: "OBSERVABILIDADE", label: "Plano de Observabilidade", icon: "eye", description: "Logs, métricas, alertas e dashboards para produção" },
    ],
    gates: [
      "Zero bugs P0 abertos no caminho crítico",
      "3 ou mais usuários reais testaram sem ajuda",
      "Core Web Vitals dentro dos benchmarks-alvo",
    ],
  },
  {
    number: 7,
    name: "DEPLOY",
    motivation: "Lance com intenção e estratégia — e chegue aos seus primeiros 10 clientes pagantes",
    tagline: "7 entregáveis de lançamento",
    artifacts: [
      { key: "RUNBOOK_DEPLOY", label: "Runbook de Deploy", icon: "terminal", description: "Pré-deploy, deploy, smoke tests, rollback e comunicação" },
      { key: "GTM", label: "Plano Go-to-Market", icon: "target", description: "Canais, mensagem, 10 primeiros clientes e métricas" },
      { key: "LAUNCH_CHECKLIST", label: "Launch Checklist", icon: "check-square", description: "Técnico, produto, marketing, legal e operacional" },
      { key: "METRICAS_POS_LAUNCH", label: "Dashboard Pós-Lançamento", icon: "bar-chart-2", description: "Métricas semana a semana nas primeiras 4 semanas" },
      { key: "PLANO_CRESCIMENTO_90_DIAS", label: "Plano de Crescimento 90 Dias", icon: "trending-up", description: "Metas, canais, experimentos e triggers de pivô" },
      { key: "PITCH_INVESTIDORES", label: "Narrativa para Investidores", icon: "presentation", description: "8 slides — problema, solução, mercado, modelo e pedido" },
      { key: "SLA_SUPORTE", label: "SLA & Plano de Suporte", icon: "headphones", description: "Canais, tempos de resposta, playbooks e FAQ inicial" },
    ],
    gates: [
      "Produto acessível em URL pública com monitoramento ativo",
      "Plano GTM com os 10 primeiros clientes identificados",
      "Runbook de rollback testado e documentado",
    ],
  },
];
