export const PHASES = [
  {
    number: 1,
    name: "IDEIA",
    motivation: "Valide se sua ideia tem potencial real de mercado antes de construir qualquer linha de código",
    tagline: "8 entregáveis estratégicos",
    artifacts: [
      { key: "LEAN_CANVAS", label: "Lean Canvas", icon: "grid", description: "9 blocos do modelo de negócio" },
      { key: "JTBD", label: "Jobs to Be Done", icon: "target", description: "O que o cliente realmente quer realizar" },
      { key: "ANALISE_COMPETITIVA", label: "Análise Competitiva", icon: "bar-chart", description: "5 concorrentes mapeados com tabela comparativa" },
      { key: "SWOT", label: "Análise SWOT", icon: "layers", description: "Forças, fraquezas, oportunidades e ameaças" },
      { key: "DIMENSIONAMENTO_MERCADO", label: "TAM / SAM / SOM", icon: "pie-chart", description: "Tamanho real do mercado com metodologia" },
      { key: "VALIDACAO_RAPIDA", label: "Script de Validação", icon: "message-square", description: "10 perguntas de entrevista para validar a hipótese" },
      { key: "HIPOTESE_CENTRAL", label: "Hipótese Central", icon: "zap", description: "Aposta principal em 1 frase testável" },
      { key: "SCORE_POTENCIAL", label: "Score de Potencial", icon: "star", description: "Avaliação 1-5 em 5 dimensões com recomendação" },
    ],
    gates: [
      "Hipótese central escrita em 1 frase testável",
      "Análise competitiva com 5 concorrentes mapeados",
      "Score de potencial médio ≥ 3.5",
    ],
  },
  {
    number: 2,
    name: "PRD",
    motivation: "Defina exatamente o que será construído e por que os usuários vão pagar por isso",
    tagline: "7 entregáveis de produto",
    artifacts: [
      { key: "PRD", label: "Product Requirements Document", icon: "file-text", description: "Documento completo com escopo e critérios de sucesso" },
      { key: "PERSONAS", label: "Personas", icon: "users", description: "3 personas detalhadas incluindo persona negativa" },
      { key: "USER_STORIES", label: "User Stories", icon: "list", description: "15 user stories com critérios de aceitação" },
      { key: "METRICAS_SUCESSO", label: "Framework de Métricas", icon: "trending-up", description: "North Star, inputs, guardrails e AARRR" },
      { key: "HIPOTESE_PRICING", label: "Estratégia de Pricing", icon: "dollar-sign", description: "3 tiers com unit economics e willingness to pay" },
      { key: "BENCHMARKING", label: "Benchmarking", icon: "globe", description: "3 referências globais com o que copiar e evitar" },
      { key: "ROADMAP_3_MESES", label: "Roadmap 3 Meses", icon: "map", description: "Plano trimestral com objetivos e entregas-chave" },
    ],
    gates: [
      "MVP cabe em ≤ 4 semanas de desenvolvimento",
      "North Star metric definida e mensurável",
      "Proposta de valor diferenciada do concorrente principal",
    ],
  },
  {
    number: 3,
    name: "SPEC",
    motivation: "Projete a arquitetura técnica antes de escrever a primeira linha de código",
    tagline: "8 entregáveis técnicos",
    artifacts: [
      { key: "ARQUITETURA", label: "Arquitetura do Sistema", icon: "cpu", description: "Stack, componentes, diagramas e trade-offs" },
      { key: "MODELO_DADOS", label: "Modelo de Dados", icon: "database", description: "Entidades, campos, índices e relacionamentos" },
      { key: "CONTRATOS_API", label: "Contratos de API", icon: "code", description: "8+ endpoints críticos documentados" },
      { key: "SEGURANCA", label: "Plano de Segurança", icon: "shield", description: "OWASP Top 10, LGPD, autenticação e auditoria" },
      { key: "FLUXOS_UI", label: "Fluxos de UX", icon: "layout", description: "5 fluxos críticos tela por tela com edge cases" },
      { key: "ESCALABILIDADE", label: "Plano de Escalabilidade", icon: "server", description: "Estratégia para 1K, 10K e 100K usuários" },
      { key: "ADR", label: "Architecture Decision Records", icon: "bookmark", description: "5 ADRs com contexto, decisão e consequências" },
      { key: "SETUP_DEVOPS", label: "DevOps & Infra", icon: "git-branch", description: "CI/CD, ambientes, observabilidade e custo estimado" },
    ],
    gates: [
      "Schema de dados completo e revisado",
      "Contratos de API definidos para todos os endpoints críticos",
      "Plano de segurança aprovado com LGPD endereçada",
    ],
  },
  {
    number: 4,
    name: "IMPLEMENTAÇÃO",
    motivation: "Quebre o produto em milestones navegáveis e construa com disciplina de engenharia",
    tagline: "7 entregáveis de engenharia",
    artifacts: [
      { key: "MILESTONES", label: "Plano de Milestones", icon: "flag", description: "5+ milestones com features, critérios e demos" },
      { key: "SPRINT_1", label: "Sprint 1 Detalhado", icon: "play", description: "Primeira semana hora a hora com bloqueadores mapeados" },
      { key: "ESTRUTURA_PASTAS", label: "Estrutura do Projeto", icon: "folder", description: "Árvore de arquivos comentada" },
      { key: "README", label: "README Completo", icon: "file", description: "Setup em 5 comandos, .env.example e contribuição" },
      { key: "GUIA_CONTRIBUICAO", label: "CONTRIBUTING.md", icon: "git-merge", description: "Padrões de código, PR checklist e convenção de commits" },
      { key: "TECH_DEBT_LOG", label: "Log de Débito Técnico", icon: "alert-triangle", description: "8+ atalhos documentados com plano de resolução" },
      { key: "DEFINITION_OF_DONE", label: "Definition of Done", icon: "check-square", description: "Critérios de conclusão para código, testes e deploy" },
    ],
    gates: [
      "Milestones quebrados em features entregáveis e testáveis",
      "README com setup funcionando em ≤ 15 minutos",
      "Zero mocks em features do caminho crítico",
    ],
  },
  {
    number: 5,
    name: "TESTE",
    motivation: "Valide que o produto funciona e que usuários reais conseguem usá-lo sem ajuda",
    tagline: "7 entregáveis de qualidade",
    artifacts: [
      { key: "PLANO_TESTES", label: "Plano de Testes", icon: "clipboard", description: "Estratégia, pirâmide, ferramentas e cobertura mínima" },
      { key: "CASOS_TESTE_CRITICOS", label: "20 Casos de Teste Críticos", icon: "check", description: "P0/P1/P2 priorizados com steps e resultados esperados" },
      { key: "CHECKLIST_QA", label: "Checklist de QA", icon: "list-checks", description: "Funcionalidade, performance, segurança, acessibilidade" },
      { key: "SCRIPT_USER_TEST", label: "Script de Teste com Usuários", icon: "user-check", description: "Roteiro para 5 testes reais com métricas de usabilidade" },
      { key: "RELATORIO_PERFORMANCE", label: "Benchmarks de Performance", icon: "activity", description: "Core Web Vitals, latência de API e carga suportada" },
      { key: "BUGS_PREVENCAO", label: "Top 10 Bugs a Prevenir", icon: "bug", description: "Causa raiz, impacto, prevenção e detecção" },
      { key: "OBSERVABILIDADE", label: "Plano de Observabilidade", icon: "eye", description: "Logs, métricas, alertas e dashboards para produção" },
    ],
    gates: [
      "Zero bugs P0 abertos no caminho crítico",
      "3 ou mais usuários reais testaram sem ajuda",
      "Core Web Vitals dentro dos benchmarks-alvo",
    ],
  },
  {
    number: 6,
    name: "DEPLOY",
    motivation: "Lance com intenção e estratégia — e chegue aos seus primeiros 10 clientes pagantes",
    tagline: "7 entregáveis de lançamento",
    artifacts: [
      { key: "RUNBOOK_DEPLOY", label: "Runbook de Deploy", icon: "terminal", description: "Pré-deploy, deploy, smoke tests, rollback e comunicação" },
      { key: "GTM", label: "Plano Go-to-Market", icon: "target", description: "Canais, mensagem, 10 primeiros clientes e métricas" },
      { key: "LAUNCH_CHECKLIST", label: "Launch Checklist", icon: "check-square", description: "Técnico, produto, marketing, legal e operacional" },
      { key: "METRICAS_POS_LAUNCH", label: "Dashboard Pós-Lançamento", icon: "bar-chart-2", description: "Métricas semana a semana nas primeiras 4 semanas" },
      { key: "PLANO_CRESCIMENTO_90_DIAS", label: "Plano de Crescimento 90 Dias", icon: "trending-up", description: "Metas, canais, experimentos e triggers de pivô" },
      { key: "PITCH_INVESTIDORES", label: "Narrativa para Investidores", icon: "presentation", description: "8 slides — problema, solução, mercado, modelo e pedido" },
      { key: "SLA_SUPORTE", label: "SLA & Plano de Suporte", icon: "headphones", description: "Canais, tempos de resposta, playbooks e FAQ inicial" },
    ],
    gates: [
      "Produto acessível em URL pública com monitoramento ativo",
      "Plano GTM com os 10 primeiros clientes identificados",
      "Runbook de rollback testado e documentado",
    ],
  },
];
